#!/usr/bin/env bash
# =============================================================================
# build_demo_rom.sh — Build một "ROM mẫu" theo đúng cấu trúc firmware Samsung
# Galaxy S9 bản Hàn (SM-G960N, mã máy starlte, chip Exynos 9810).
#
# MỤC ĐÍCH: HỌC CẤU TRÚC ROM. Kernel bên trong là file giả, KHÔNG khởi động được.
# ⚠️  TUYỆT ĐỐI KHÔNG FLASH FILE TẠO RA BỞI SCRIPT NÀY VÀO ĐIỆN THOẠI.
#
# Cần (Ubuntu): sudo apt install e2fsprogs android-sdk-libsparse-utils lz4 \
#                                cpio mkbootimg zip
# Chạy:         ./build_demo_rom.sh      → kết quả nằm trong ./out/
# =============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/out"
WORK="$OUT/work"

# ----------------------------------------------------------------------------
# Thông số của ROM (đổi ở đây để thấy nó chảy vào build.prop, boot.img...)
# ----------------------------------------------------------------------------
MODEL="SM-G960N"              # Số model: G960 = S9, N = bản Hàn Quốc
DEVICE="starlte"              # Mã máy (codename) của S9
PRODUCT="starlteks"           # Tên sản phẩm: starlte + ks (Korea)
PLATFORM="exynos9810"         # Chip
HARDWARE="samsungexynos9810"  # Giá trị androidboot.hardware / ro.hardware
ANDROID_VER="10"              # Phiên bản Android
SDK_VER="29"                  # API level tương ứng Android 10
BUILD_ID="QP1A.190711.020"    # Mã build của Google (nhánh Android 10)
PDA="G960NKSU9DEMO1"          # Phiên bản firmware Samsung (bản DEMO)
SECURITY_PATCH="2021-11-01"   # Mức bản vá bảo mật
BUILD_DATE_UTC="$(date -u +%s)"
FINGERPRINT="samsung/${PRODUCT}/${DEVICE}:${ANDROID_VER}/${BUILD_ID}/${PDA}:user/release-keys"

need() { command -v "$1" >/dev/null || { echo "Thiếu công cụ: $1 (xem đầu file để cài)"; exit 1; }; }
for t in mkfs.ext4 img2simg lz4 cpio mkbootimg tar md5sum zip gzip; do need "$t"; done

step() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

rm -rf "$OUT"
mkdir -p "$WORK" "$OUT/odin" "$OUT/recovery_zip"

# ============================================================================
# 1. PHÂN VÙNG SYSTEM — chứa Android framework, app hệ thống, build.prop
#    Android 10 dùng "system-as-root": gốc của system.img chính là "/" của
#    máy, còn thư mục /system nằm bên trong nó.
# ============================================================================
step "1. Tạo cây thư mục phân vùng SYSTEM"
SYS="$WORK/system_root"
mkdir -p "$SYS"/{system/{app,priv-app,framework,bin,lib,lib64,etc/permissions,fonts,media/audio/ringtones,csc},dev,proc,sys,data,vendor,odm}

cat > "$SYS/system/build.prop" <<EOF
# begin build properties
# autogenerated by build_demo_rom.sh (ROM MẪU — KHÔNG FLASH)
ro.system.build.date.utc=${BUILD_DATE_UTC}
ro.system.build.fingerprint=${FINGERPRINT}
ro.system.build.id=${BUILD_ID}
ro.system.build.type=user
ro.system.build.tags=release-keys
ro.system.build.version.release=${ANDROID_VER}
ro.system.build.version.sdk=${SDK_VER}
ro.system.build.version.incremental=${PDA}
ro.build.id=${BUILD_ID}
ro.build.display.id=${BUILD_ID}.${PDA}
ro.build.version.incremental=${PDA}
ro.build.version.sdk=${SDK_VER}
ro.build.version.release=${ANDROID_VER}
ro.build.version.security_patch=${SECURITY_PATCH}
ro.build.type=user
ro.build.tags=release-keys
ro.build.date.utc=${BUILD_DATE_UTC}
ro.build.fingerprint=${FINGERPRINT}
ro.build.PDA=${PDA}
ro.build.characteristics=phone,emulator
ro.product.system.brand=samsung
ro.product.system.manufacturer=samsung
ro.product.system.model=${MODEL}
ro.product.system.name=${PRODUCT}
ro.product.system.device=${DEVICE}
ro.product.locale=ko-KR
ro.product.first_api_level=26
# end build properties

# ---- Thông số hệ thống (có thể chỉnh khi mod) ----
ro.sf.lcd_density=640
dalvik.vm.heapstartsize=8m
dalvik.vm.heapgrowthlimit=256m
dalvik.vm.heapsize=512m
ro.config.ringtone=Over_the_Horizon.ogg
ro.config.notification_sound=Skyline.ogg
persist.sys.timezone=Asia/Seoul
ro.com.google.clientidbase=android-samsung
EOF

# App hệ thống: mỗi app một thư mục chứa file .apk (ở đây là file giả)
for app in SamsungCamera SecSettings KakaoTalk_Preload TWorld_Preload; do
  mkdir -p "$SYS/system/app/$app"
  echo "DEMO APK: $app" > "$SYS/system/app/$app/$app.apk"
done
for app in SystemUI Telecom; do
  mkdir -p "$SYS/system/priv-app/$app"
  echo "DEMO PRIV-APK: $app" > "$SYS/system/priv-app/$app/$app.apk"
done
echo "DEMO framework" > "$SYS/system/framework/framework.jar"
echo "DEMO font"      > "$SYS/system/fonts/Roboto-Regular.ttf"
echo "DEMO ringtone"  > "$SYS/system/media/audio/ringtones/Over_the_Horizon.ogg"
cat > "$SYS/system/etc/permissions/demo_features.xml" <<'EOF'
<?xml version="1.0" encoding="utf-8"?>
<!-- Khai báo tính năng phần cứng máy có (app dùng để kiểm tra) -->
<permissions>
    <feature name="android.hardware.nfc" />
    <feature name="android.hardware.camera.front" />
    <feature name="android.hardware.fingerprint" />
</permissions>
EOF
mkdir -p "$SYS/system/csc"
echo "KOO" > "$SYS/system/csc/sales_code.dat"

# ============================================================================
# 2. PHÂN VÙNG VENDOR — driver, thư viện phần cứng riêng của Samsung/Exynos
# ============================================================================
step "2. Tạo cây thư mục phân vùng VENDOR"
VND="$WORK/vendor"
mkdir -p "$VND"/{etc/init,firmware,lib,lib64/hw,bin/hw}
cat > "$VND/build.prop" <<EOF
# vendor build properties (ROM MẪU)
ro.vendor.build.fingerprint=${FINGERPRINT}
ro.vendor.build.version.release=${ANDROID_VER}
ro.vendor.build.version.sdk=${SDK_VER}
ro.product.vendor.brand=samsung
ro.product.vendor.manufacturer=samsung
ro.product.vendor.model=${MODEL}
ro.product.vendor.name=${PRODUCT}
ro.product.vendor.device=${DEVICE}
ro.product.board=universal9810
ro.board.platform=exynos5
ro.hardware.chipname=${PLATFORM}
EOF
# fstab: bảng khai báo phân vùng nào mount vào đâu, định dạng gì
cat > "$VND/etc/fstab.${HARDWARE}" <<'EOF'
# <src>                                          <mnt_point> <type> <mnt_flags>          <fs_mgr_flags>
/dev/block/platform/11120000.ufs/by-name/SYSTEM   /           ext4   ro,errors=panic      wait,verify
/dev/block/platform/11120000.ufs/by-name/VENDOR   /vendor     ext4   ro,errors=panic      wait,verify
/dev/block/platform/11120000.ufs/by-name/ODM      /odm        ext4   ro,errors=panic      wait,verify
/dev/block/platform/11120000.ufs/by-name/CACHE    /cache      ext4   nosuid,nodev,noatime wait,check
/dev/block/platform/11120000.ufs/by-name/USERDATA /data       ext4   nosuid,nodev,noatime wait,check,fileencryption=ice
/dev/block/platform/11120000.ufs/by-name/EFS      /mnt/vendor/efs ext4 nosuid,nodev,noatime wait,check
EOF
echo "DEMO GPU driver (Mali-G72)" > "$VND/lib64/hw/gralloc.${PLATFORM}.so"
echo "DEMO wifi firmware"         > "$VND/firmware/wifi_fw.bin"

# ============================================================================
# 3. Đóng gói ext4 → sparse image (định dạng Samsung/Odin dùng)
# ============================================================================
make_img() {  # $1=thư mục nguồn  $2=tên phân vùng  $3=kích thước
  local raw="$WORK/$2.raw.img"
  mkfs.ext4 -q -F -L "$2" -d "$1" "$raw" "$3"   # ảnh ext4 thô, kích thước đầy đủ
  img2simg "$raw" "$WORK/$2.img.ext4"           # nén dạng sparse (bỏ block trống)
  printf '    %-8s raw ext4: %6s  →  sparse: %6s\n' "$2" \
    "$(du -h --apparent-size "$raw" | cut -f1)" "$(du -h "$WORK/$2.img.ext4" | cut -f1)"
}
step "3. Đóng gói SYSTEM/VENDOR thành ảnh ext4 rồi chuyển sang sparse"
make_img "$SYS" system 64M
make_img "$VND" vendor 16M

# ============================================================================
# 4. BOOT.IMG — kernel + ramdisk + cmdline (thứ bootloader nạp đầu tiên)
# ============================================================================
step "4. Tạo boot.img (kernel GIẢ + ramdisk)"
RD="$WORK/ramdisk"
mkdir -p "$RD"/{dev,proc,sys,system,vendor,data}
cat > "$RD/init.rc" <<'EOF'
# init.rc — kịch bản khởi động đầu tiên do tiến trình init (PID 1) đọc
on early-init
    start ueventd
on init
    mkdir /mnt/vendor/efs 0771 radio system
on fs
    mount_all /vendor/etc/fstab.${ro.hardware}
on boot
    class_start core
EOF
echo "ro.debuggable=0" > "$RD/prop.default"
( cd "$RD" && find . | cpio -o -H newc --quiet | gzip -9 > "$WORK/ramdisk.cpio.gz" )
# Kernel thật là file "Image" ARM64 ~20MB. Ở đây chỉ là file chữ.
printf 'DEMO KERNEL - KHONG KHOI DONG DUOC\n' > "$WORK/kernel"

# Gói mkbootimg của Ubuntu 24.04 thiếu module "gki" (chỉ dùng cho boot v4).
# Tạo module rỗng thay thế để mkbootimg chạy được với header v1.
mkdir -p "$WORK/pystub/gki"
touch "$WORK/pystub/gki/__init__.py"
echo 'def generate_gki_certificate(*a, **k): raise NotImplementedError' \
  > "$WORK/pystub/gki/generate_gki_certificate.py"

# Thông số mkbootimg tham khảo từ device tree starlte (TWRP/LineageOS)
BOOT_CMDLINE="androidboot.hardware=${HARDWARE} androidboot.selinux=enforcing loop.max_part=7"
PYTHONPATH="$WORK/pystub${PYTHONPATH:+:$PYTHONPATH}" mkbootimg \
  --header_version 1 \
  --kernel  "$WORK/kernel" \
  --ramdisk "$WORK/ramdisk.cpio.gz" \
  --cmdline "$BOOT_CMDLINE" \
  --base 0x10000000 --pagesize 2048 \
  --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100 \
  --os_version "${ANDROID_VER}.0.0" --os_patch_level "${SECURITY_PATCH%-*}" \
  --board "SRPQH16A000KU" \
  -o "$WORK/boot.img"
# Samsung đánh dấu ảnh đã ký bằng chuỗi này ở cuối file
printf 'SEANDROIDENFORCE' >> "$WORK/boot.img"
echo "    boot.img: $(du -h "$WORK/boot.img" | cut -f1)"

# ============================================================================
# 5. Nén lz4 + đóng gói tar.md5 — định dạng file AP_... mà Odin nhận
# ============================================================================
step "5. Nén lz4 và đóng gói thành AP_*.tar.md5 (định dạng Odin)"
STAGE="$WORK/ap_stage"; mkdir -p "$STAGE"
lz4 -q -B6 --content-size "$WORK/boot.img"          "$STAGE/boot.img.lz4"
lz4 -q -B6 --content-size "$WORK/system.img.ext4"   "$STAGE/system.img.ext4.lz4"
lz4 -q -B6 --content-size "$WORK/vendor.img.ext4"   "$STAGE/vendor.img.ext4.lz4"
mkdir -p "$STAGE/meta-data"
cat > "$STAGE/meta-data/README_DEMO.txt" <<EOF
ROM MAU tao boi build_demo_rom.sh — KHONG DUOC FLASH
Model=${MODEL} Device=${DEVICE} PDA=${PDA}
EOF

AP_NAME="AP_${PDA}_DEMO_KHONG_FLASH.tar"
( cd "$STAGE" && tar -H ustar -cf "$OUT/odin/$AP_NAME" boot.img.lz4 system.img.ext4.lz4 vendor.img.ext4.lz4 meta-data )
# .tar.md5 = file tar + 1 dòng MD5 nối vào cuối để Odin kiểm tra toàn vẹn
( cd "$OUT/odin" && md5sum -t "$AP_NAME" >> "$AP_NAME" && mv "$AP_NAME" "$AP_NAME.md5" )
ls -lh "$OUT/odin"

# ============================================================================
# 6. Dạng thứ hai: ZIP flash qua recovery (TWRP) — kiểu LineageOS, ROM cook
# ============================================================================
step "6. Tạo dạng ROM ZIP (flash qua TWRP) để so sánh"
ZIPD="$WORK/zip"
mkdir -p "$ZIPD/META-INF/com/google/android"
cp "$WORK/boot.img" "$ZIPD/boot.img"
# Custom ROM thật thường dùng system.new.dat.br + system.transfer.list;
# ở đây để ảnh sparse cho đơn giản.
cp "$WORK/system.img.ext4" "$ZIPD/system.img"
cp "$WORK/vendor.img.ext4" "$ZIPD/vendor.img"
cat > "$ZIPD/META-INF/com/google/android/updater-script" <<EOF
# updater-script: TWRP chạy từng lệnh này khi flash ZIP (cú pháp edify)
assert(getprop("ro.product.device") == "${DEVICE}" || abort("Sai máy! ROM này chỉ cho ${DEVICE}"));
ui_print("ROM MAU - KHONG FLASH THAT");
ui_print("Dang ghi system...");
package_extract_file("system.img", "/dev/block/platform/11120000.ufs/by-name/SYSTEM");
ui_print("Dang ghi vendor...");
package_extract_file("vendor.img", "/dev/block/platform/11120000.ufs/by-name/VENDOR");
ui_print("Dang ghi boot...");
package_extract_file("boot.img", "/dev/block/platform/11120000.ufs/by-name/BOOT");
EOF
# update-binary thật là file ELF chạy updater-script; ở đây là script chặn lại
cat > "$ZIPD/META-INF/com/google/android/update-binary" <<'EOF'
#!/sbin/sh
echo "ui_print ROM MAU - dung lai, khong ghi gi ca" > /proc/self/fd/$2
exit 1
EOF
( cd "$ZIPD" && zip -qr9 "$OUT/recovery_zip/ROM_${DEVICE}_DEMO_KHONG_FLASH.zip" . )
ls -lh "$OUT/recovery_zip"

step "XONG. Mổ xẻ lại ROM vừa build bằng:"
echo "    ./inspect_rom.sh out/odin/$AP_NAME.md5"
